version: "3"

services:
  app:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: dockerfile
    command: python3 app.py
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/apps/tcc
    restart: always