version: "3"

services:
  app:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: dockerfile
    command: flask --app src/app/app.py run --host=0.0.0.0
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/apps/tcc
    restart: always